env: order-dev999.yml
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///pm111?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  application:
    name: order
server:
  port: 8082
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

