env: order-dev777999.yml
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.2.106:3306/pm111?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.2.106
    username: guest
    password: guest
    port: 5672
  application:
    name: order
server:
  port: 8087
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

